server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: financial-management-system
  
  # MySQL配置
  datasource:
    url: jdbc:mysql://localhost:3306/financial_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  # MongoDB配置
  data:
    mongodb:
      host: localhost
      port: 27017
      database: financial_logs
  
  # Security配置
  security:
    user:
      name: admin
      password: admin123

# 日志配置
logging:
  level:
    com.company.financial: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"