server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: financial-management-system
  
  # MySQL配置
  datasource:
    url: jdbc:mysql://127.0.0.1:12100/financial_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: bunny
    password: bunny
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  
  # Security配置
  security:
    user:
      name: admin
      password: admin123

# JWT配置
jwt:
  secret: dGhpc0lzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JKV1RIUzUxMkFsZ29yaXRobVRoYXRJc0F0TGVhc3Q2NEJ5dGVzTG9uZ0ZvclNlY3VyaXR5UHVycG9zZXM=
  expiration: 86400 # 24小时（秒）
  refresh-expiration: 604800 # 7天（秒）
  header: Authorization
  prefix: Bearer
  issuer: financial-management-system

# 日志配置
logging:
  level:
    com.company.financial: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"